In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, LabelEncoder, StandardScaler
from sklearn.model_selection import train_test_split    # Because train test split s 

##### Step 1 - Importing Data

In [2]:
dataset = pd.read_csv("./Machine-Learning-A-Z-Codes-Datasets/Part 1 - Data Preprocessing/Section 2 -------------------- Part 1 - Data Preprocessing --------------------/Python/Data.csv")

FileNotFoundError: [Errno 2] No such file or directory: './Machine-Learning-A-Z-Codes-Datasets/Part 1 - Data Preprocessing/Section 2 -------------------- Part 1 - Data Preprocessing --------------------/Python/Data.csv'

In [ ]:
dataset.head()

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes

##### Step 2 - Divide data into Features and Result vector

In [ ]:
X = dataset.iloc[:,:-1] #The colon here means range, a range in python includes the lower bound but exclude the upper bound
Y = dataset.iloc[:,-1]  #When we want only one particular column, we give the index of that particular column  


In [ ]:
print(type(X))
print(type(X.to_numpy()))
print(type(X.values))

<class 'pandas.core.frame.DataFrame'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [ ]:
X = X.to_numpy()
Y = Y.to_numpy()

##### Step 3 - Taking care of missing data

Imputing Numerical Data

In [ ]:
imputer = SimpleImputer(missing_values=np.nan, strategy="mean")

# Now we will use the "fit" method to apply this imputer to the matrix of features

imputer.fit(X=X[:,1:3]) #Learns how to Fit only expects all the columns with numerical values because we have used the imputer for the same


SimpleImputer()

In [ ]:
X[:, 1:3] = imputer.transform(X=X[:, 1:3]) #Transforms the data using the imputer in the specified columns

In [ ]:
X

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, 63777.77777777778],
       ['France', 35.0, 58000.0],
       ['Spain', 38.77777777777778, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

##### Step 4 - Encoding Categorical data

Encoding Categorical Data - One Hot Encoding
- One hot encoding consists of binary column of each of the following inputs
example - [0,1,0],[1,0,0],[0,0,1]

In [ ]:
ct = ColumnTransformer(transformers=[("encoder", OneHotEncoder(), [0])],remainder="passthrough")

In [ ]:
X= ct.fit_transform(X=X)

In [ ]:
X

array([[1.0, 0.0, 0.0, 44.0, 72000.0],
       [0.0, 0.0, 1.0, 27.0, 48000.0],
       [0.0, 1.0, 0.0, 30.0, 54000.0],
       [0.0, 0.0, 1.0, 38.0, 61000.0],
       [0.0, 1.0, 0.0, 40.0, 63777.77777777778],
       [1.0, 0.0, 0.0, 35.0, 58000.0],
       [0.0, 0.0, 1.0, 38.77777777777778, 52000.0],
       [1.0, 0.0, 0.0, 48.0, 79000.0],
       [0.0, 1.0, 0.0, 50.0, 83000.0],
       [1.0, 0.0, 0.0, 37.0, 67000.0]], dtype=object)

Encoding Labels - Label Encoder

In [ ]:
le = LabelEncoder()
Y = le.fit_transform(y=Y)

In [ ]:
Y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

##### Step 5 - Splitting the data into training and test set.
<p style="color: yellow;">This a part of evaluation process and not of data preprocessing. Therefore this function is not inside preprocessing module of scikit-learn </p>

In [ ]:
X_train, X_test, Y_train, Y_test = train_test_split(X,Y, test_size=0.2, shuffle=True, random_state=1)  #Instead of test_size = 0.2, we can also give train_size = 0.8

In [ ]:
print(X_train)

[[0.0 0.0 1.0 38.77777777777778 52000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 35.0 58000.0]]


In [ ]:
print(X_test)

[[0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


In [ ]:
print(Y_train)

[0 1 0 0 1 1 0 1]


In [ ]:
print(Y_test)

[0 1]


##### Step 6 - Feature Scaling

In [ ]:
sc = StandardScaler()
X_train[:, 3:] = sc.fit_transform(X_train[:, 3:])
X_train

array([[0.0, 0.0, 1.0, -0.19159184384578545, -1.0781259408412425],
       [0.0, 1.0, 0.0, -0.014117293757057777, -0.07013167641635372],
       [1.0, 0.0, 0.0, 0.566708506533324, 0.633562432710455],
       [0.0, 0.0, 1.0, -0.30453019390224867, -0.30786617274297867],
       [0.0, 0.0, 1.0, -1.9018011447007988, -1.420463615551582],
       [1.0, 0.0, 0.0, 1.1475343068237058, 1.232653363453549],
       [0.0, 1.0, 0.0, 1.4379472069688968, 1.5749910381638885],
       [1.0, 0.0, 0.0, -0.7401495441200351, -0.5646194287757332]],
      dtype=object)

In [ ]:
X_test[:, 3:] = sc.transform(X_test[:, 3:])
X_test

array([[0.0, 1.0, 0.0, -1.4661817944830124, -0.9069571034860727],
       [1.0, 0.0, 0.0, -0.44973664397484414, 0.2056403393225306]],
      dtype=object)

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from xgboost import XGBRegressor
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
from sklearn.model_selection import train_test_split

# Generate synthetic data (or replace with actual stock data)
np.random.seed(42)
days = np.arange(1, 101).reshape(-1, 1)  # 100 days
prices = 100 + np.sin(days / 10) * 10 + np.random.normal(0, 1.5, size=(100,))  # actual prices

# Split the data
X_train, X_test, y_train, y_test = train_test_split(days, prices, test_size=0.2, random_state=42)

# --- XGBoost Model ---
xgb_model = XGBRegressor()
xgb_model.fit(X_train, y_train)
xgb_pred = xgb_model.predict(days)

# --- Polynomial Regression Model ---
poly = PolynomialFeatures(degree=3)
X_poly = poly.fit_transform(days)
lin_reg = LinearRegression()
lin_reg.fit(X_poly, prices)
poly_pred = lin_reg.predict(X_poly)

# --- Plotting ---
plt.figure(figsize=(14, 6))

# XGBoost Chart
plt.subplot(1, 2, 1)
plt.plot(days, prices, label="Actual Price", color='blue')
plt.plot(days, xgb_pred, label="XGBoost Predicted", color='orange')
plt.title("Actual vs Predicted Stock Price (XGBoost)")
plt.xlabel("Days")
plt.ylabel("Price")
plt.legend()
plt.grid(True)

# Polynomial Regression Chart
plt.subplot(1, 2, 2)
plt.plot(days, prices, label="Actual Price", color='blue')
plt.plot(days, poly_pred, label="Polynomial Regression", color='green')
plt.title("Actual vs Predicted Stock Price (Polynomial Regression)")
plt.xlabel("Days")
plt.ylabel("Price")
plt.legend()
plt.grid(True)

plt.tight_layout()
plt.show()


ModuleNotFoundError: No module named 'xgboost'